# Ruff configuration
target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "C4", "SIM", "TCH", "PL"]
ignore = ["E501"]  # line too long - we use 100 char limit

[format]
quote-style = "double"
indent-style = "space"